{% set version="0.3.3" %}

package:
  name: usher
  version: {{ version }}

source:
  - url: https://github.com/yatisht/usher/archive/v{{ version  }}.tar.gz
    sha256: 6067c558e02a23c35028aad87a8b72d4aed2e170536e311f1c560dd02fa3994f

build:
  number: 0

requirements:
  build:
    - make
    - autoconf
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - wget
  host:
    - boost-cpp
    - libprotobuf
  run:
    - python
    - mafft
    - biopython
    - boost-cpp
    - ucsc-fatovcf

test:
  commands:
    - usher --help
    - matOptimize --help
    - matUtils --help

about:
  home: https://github.com/yatisht/usher
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Ultrafast Sample Placement on Existing Trees (UShER)
